# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MarkGingrass.com
email: mark.gingrass@gmail.com
description:  #> # this means to ignore newlines until "baseurl:"
  - Udacity Self-Driving Car Engineer Nanodegree Est Completion 2018 <br>
  - Master's in Business Administration / BS Avionics Management <br>
  - Operations Researcher (2 years), Supply Chain Management (8 years), Engineering Technician (7 years)
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:year/:month/:day/:title.html
#PRODUCTION
#url: "http://markgingrass.com" # the base hostname & protocol for your site
#DEV
url: "../" # the base hostname & protocol for your site
twitter_username:  MarkGingrass
github_username:   mtgingrass
linkedin_username: markgingrass

# Build settings
markdown: kramdown
